Repository TheSirLancelot/Netulla, pull requests merged in 2023-11, with the labels that each got.

#66 43 make the splash page pretty
  Home.py
  images/Netulla.png
  images/favicon.png
  requirements.txt
  tests/requirements.txt
  tests/test_frontend.py
Labels: bug, enhancement

#78 Update living documents
  CurrentProjectStatus.md
  ProjectSummary.md
  TestPlan.md
  tests/test_frontend.py
Labels: documentation

#84 removed special character
  tests/test_frontend.py
Labels: enhancement

#83 changed wget to curl throughout
  CurrentProjectStatus.md
  ProjectSummary.md
  TestPlan.md
  tests/test_frontend.py
Labels: documentation

#79 Update README.md
  DockerCommands.md
  README.md
Labels: documentation
